// Complete, verified surah name table (1–114) used to power robust search.
//
// The alquran.cloud API only returns the Arabic name (with diacritics), an
// English transliteration, and an English meaning. It has NO Kurdish name and
// the transliteration spellings are inconsistent (e.g. "Al-Fatiha" vs
// "Faatiha"). This table provides extra searchable aliases per surah —
// Arabic (clean), Kurdish, and common English spelling variants — so users can
// find any surah by typing its name in Arabic, Kurdish, or English.
//
// Each `aliases` array is matched (after normalization) in addition to the
// API-provided fields. Spelling is intentionally generous to maximize hits.

export interface SurahAliases {
  ar: string; // clean Arabic name (no diacritics)
  ku: string; // Kurdish (Sorani) name
  en: string[]; // English transliteration variants
}

// Indexed by surah number (1–114).
export const SURAH_ALIASES: Record<number, SurahAliases> = {
  1: { ar: 'الفاتحة', ku: 'فاتیحە', en: ['al-fatiha', 'fatiha', 'al fatihah', 'faatiha'] },
  2: { ar: 'البقرة', ku: 'بەقەرە', en: ['al-baqarah', 'baqarah', 'baqara', 'the cow'] },
  3: { ar: 'آل عمران', ku: 'ئالی عیمران', en: ['aal-e-imran', 'al-imran', 'imran', 'ali imran'] },
  4: { ar: 'النساء', ku: 'نیسا', en: ['an-nisa', 'nisa', 'the women'] },
  5: { ar: 'المائدة', ku: 'مائیدە', en: ['al-maidah', 'maidah', 'maeda', 'the table'] },
  6: { ar: 'الأنعام', ku: 'ئەنعام', en: ['al-anam', 'anam', 'the cattle'] },
  7: { ar: 'الأعراف', ku: 'ئەعراف', en: ['al-araf', 'araf', 'the heights'] },
  8: { ar: 'الأنفال', ku: 'ئەنفال', en: ['al-anfal', 'anfal', 'the spoils'] },
  9: { ar: 'التوبة', ku: 'تەوبە', en: ['at-tawbah', 'tawbah', 'tauba', 'the repentance'] },
  10: { ar: 'يونس', ku: 'یونس', en: ['yunus', 'jonah'] },
  11: { ar: 'هود', ku: 'هود', en: ['hud'] },
  12: { ar: 'يوسف', ku: 'یوسف', en: ['yusuf', 'joseph'] },
  13: { ar: 'الرعد', ku: 'ڕەعد', en: ['ar-rad', 'rad', 'the thunder'] },
  14: { ar: 'إبراهيم', ku: 'ئیبراهیم', en: ['ibrahim', 'abraham'] },
  15: { ar: 'الحجر', ku: 'حیجر', en: ['al-hijr', 'hijr'] },
  16: { ar: 'النحل', ku: 'نەحل', en: ['an-nahl', 'nahl', 'the bee'] },
  17: { ar: 'الإسراء', ku: 'ئیسرا', en: ['al-isra', 'isra', 'the night journey'] },
  18: { ar: 'الكهف', ku: 'کەهف', en: ['al-kahf', 'kahf', 'the cave'] },
  19: { ar: 'مريم', ku: 'مەریەم', en: ['maryam', 'mary'] },
  20: { ar: 'طه', ku: 'تاها', en: ['ta-ha', 'taha'] },
  21: { ar: 'الأنبياء', ku: 'ئەنبیا', en: ['al-anbiya', 'anbiya', 'the prophets'] },
  22: { ar: 'الحج', ku: 'حەج', en: ['al-hajj', 'hajj', 'the pilgrimage'] },
  23: { ar: 'المؤمنون', ku: 'مۆئمینون', en: ['al-muminun', 'muminun', 'the believers'] },
  24: { ar: 'النور', ku: 'نوور', en: ['an-nur', 'nur', 'the light'] },
  25: { ar: 'الفرقان', ku: 'فورقان', en: ['al-furqan', 'furqan', 'the criterion'] },
  26: { ar: 'الشعراء', ku: 'شوعەرا', en: ['ash-shuara', 'shuara', 'the poets'] },
  27: { ar: 'النمل', ku: 'نەمل', en: ['an-naml', 'naml', 'the ant'] },
  28: { ar: 'القصص', ku: 'قەسەس', en: ['al-qasas', 'qasas', 'the stories'] },
  29: { ar: 'العنكبوت', ku: 'عەنکەبوت', en: ['al-ankabut', 'ankabut', 'the spider'] },
  30: { ar: 'الروم', ku: 'ڕۆم', en: ['ar-rum', 'rum', 'the romans'] },
  31: { ar: 'لقمان', ku: 'لوقمان', en: ['luqman', 'lukman'] },
  32: { ar: 'السجدة', ku: 'سەجدە', en: ['as-sajdah', 'sajdah', 'the prostration'] },
  33: { ar: 'الأحزاب', ku: 'ئەحزاب', en: ['al-ahzab', 'ahzab', 'the combined forces'] },
  34: { ar: 'سبأ', ku: 'سەبە', en: ['saba', 'sheba'] },
  35: { ar: 'فاطر', ku: 'فاتیر', en: ['fatir', 'the originator'] },
  36: { ar: 'يس', ku: 'یاسین', en: ['ya-sin', 'yasin', 'yaseen'] },
  37: { ar: 'الصافات', ku: 'ساففات', en: ['as-saffat', 'saffat'] },
  38: { ar: 'ص', ku: 'ساد', en: ['sad', 'saad'] },
  39: { ar: 'الزمر', ku: 'زومەر', en: ['az-zumar', 'zumar', 'the groups'] },
  40: { ar: 'غافر', ku: 'غافیر', en: ['ghafir', 'the forgiver'] },
  41: { ar: 'فصلت', ku: 'فوسسیلەت', en: ['fussilat', 'fussilet'] },
  42: { ar: 'الشورى', ku: 'شورا', en: ['ash-shura', 'shura', 'the consultation'] },
  43: { ar: 'الزخرف', ku: 'زوخرۆف', en: ['az-zukhruf', 'zukhruf', 'the ornaments'] },
  44: { ar: 'الدخان', ku: 'دوخان', en: ['ad-dukhan', 'dukhan', 'the smoke'] },
  45: { ar: 'الجاثية', ku: 'جاسیە', en: ['al-jathiyah', 'jathiyah', 'the kneeling'] },
  46: { ar: 'الأحقاف', ku: 'ئەحقاف', en: ['al-ahqaf', 'ahqaf'] },
  47: { ar: 'محمد', ku: 'موحەممەد', en: ['muhammad', 'mohammed'] },
  48: { ar: 'الفتح', ku: 'فەتح', en: ['al-fath', 'fath', 'the victory'] },
  49: { ar: 'الحجرات', ku: 'حوجورات', en: ['al-hujurat', 'hujurat', 'the rooms'] },
  50: { ar: 'ق', ku: 'قاف', en: ['qaf', 'kaf'] },
  51: { ar: 'الذاريات', ku: 'زاریات', en: ['adh-dhariyat', 'dhariyat', 'zariyat'] },
  52: { ar: 'الطور', ku: 'تور', en: ['at-tur', 'tur', 'the mount'] },
  53: { ar: 'النجم', ku: 'نەجم', en: ['an-najm', 'najm', 'the star'] },
  54: { ar: 'القمر', ku: 'قەمەر', en: ['al-qamar', 'qamar', 'the moon'] },
  55: { ar: 'الرحمن', ku: 'ڕەحمان', en: ['ar-rahman', 'rahman', 'the most merciful'] },
  56: { ar: 'الواقعة', ku: 'واقیعە', en: ['al-waqiah', 'waqiah', 'the inevitable'] },
  57: { ar: 'الحديد', ku: 'حەدید', en: ['al-hadid', 'hadid', 'the iron'] },
  58: { ar: 'المجادلة', ku: 'موجادەلە', en: ['al-mujadila', 'mujadila', 'the pleading woman'] },
  59: { ar: 'الحشر', ku: 'حەشر', en: ['al-hashr', 'hashr', 'the exile'] },
  60: { ar: 'الممتحنة', ku: 'مومتەحینە', en: ['al-mumtahanah', 'mumtahanah', 'she that is to be examined'] },
  61: { ar: 'الصف', ku: 'سەفف', en: ['as-saff', 'saff', 'the ranks'] },
  62: { ar: 'الجمعة', ku: 'جوموعە', en: ['al-jumuah', 'jumuah', 'friday'] },
  63: { ar: 'المنافقون', ku: 'مونافیقون', en: ['al-munafiqun', 'munafiqun', 'the hypocrites'] },
  64: { ar: 'التغابن', ku: 'تەغابون', en: ['at-taghabun', 'taghabun', 'mutual disillusion'] },
  65: { ar: 'الطلاق', ku: 'تەلاق', en: ['at-talaq', 'talaq', 'divorce'] },
  66: { ar: 'التحريم', ku: 'تەحریم', en: ['at-tahrim', 'tahrim', 'the prohibition'] },
  67: { ar: 'الملك', ku: 'مولک', en: ['al-mulk', 'mulk', 'the sovereignty'] },
  68: { ar: 'القلم', ku: 'قەلەم', en: ['al-qalam', 'qalam', 'the pen'] },
  69: { ar: 'الحاقة', ku: 'حاققە', en: ['al-haqqah', 'haqqah', 'the reality'] },
  70: { ar: 'المعارج', ku: 'مەعاریج', en: ['al-maarij', 'maarij', 'the ascending stairways'] },
  71: { ar: 'نوح', ku: 'نوح', en: ['nuh', 'noah'] },
  72: { ar: 'الجن', ku: 'جینن', en: ['al-jinn', 'jinn', 'the jinn'] },
  73: { ar: 'المزمل', ku: 'موززەممیل', en: ['al-muzzammil', 'muzzammil', 'the enshrouded one'] },
  74: { ar: 'المدثر', ku: 'مودەسسیر', en: ['al-muddaththir', 'muddaththir', 'the cloaked one'] },
  75: { ar: 'القيامة', ku: 'قییامە', en: ['al-qiyamah', 'qiyamah', 'the resurrection'] },
  76: { ar: 'الإنسان', ku: 'ئینسان', en: ['al-insan', 'insan', 'man', 'the human'] },
  77: { ar: 'المرسلات', ku: 'مورسەلات', en: ['al-mursalat', 'mursalat', 'the emissaries'] },
  78: { ar: 'النبأ', ku: 'نەبە', en: ['an-naba', 'naba', 'the tidings'] },
  79: { ar: 'النازعات', ku: 'نازیعات', en: ['an-naziat', 'naziat', 'those who drag forth'] },
  80: { ar: 'عبس', ku: 'عەبەسە', en: ['abasa', 'he frowned'] },
  81: { ar: 'التكوير', ku: 'تەکویر', en: ['at-takwir', 'takwir', 'the overthrowing'] },
  82: { ar: 'الإنفطار', ku: 'ئینفیتار', en: ['al-infitar', 'infitar', 'the cleaving'] },
  83: { ar: 'المطففين', ku: 'موتەففیفین', en: ['al-mutaffifin', 'mutaffifin', 'the defrauding'] },
  84: { ar: 'الإنشقاق', ku: 'ئینشیقاق', en: ['al-inshiqaq', 'inshiqaq', 'the sundering'] },
  85: { ar: 'البروج', ku: 'بوروج', en: ['al-buruj', 'buruj', 'the mansions of the stars'] },
  86: { ar: 'الطارق', ku: 'تاریق', en: ['at-tariq', 'tariq', 'the nightcomer'] },
  87: { ar: 'الأعلى', ku: 'ئەعلا', en: ['al-ala', 'ala', 'the most high'] },
  88: { ar: 'الغاشية', ku: 'غاشییە', en: ['al-ghashiyah', 'ghashiyah', 'the overwhelming'] },
  89: { ar: 'الفجر', ku: 'فەجر', en: ['al-fajr', 'fajr', 'the dawn'] },
  90: { ar: 'البلد', ku: 'بەلەد', en: ['al-balad', 'balad', 'the city'] },
  91: { ar: 'الشمس', ku: 'شەمس', en: ['ash-shams', 'shams', 'the sun'] },
  92: { ar: 'الليل', ku: 'لەیل', en: ['al-layl', 'layl', 'the night'] },
  93: { ar: 'الضحى', ku: 'زوحا', en: ['ad-duha', 'duha', 'the morning hours'] },
  94: { ar: 'الشرح', ku: 'شەرح', en: ['ash-sharh', 'sharh', 'inshirah', 'the relief'] },
  95: { ar: 'التين', ku: 'تین', en: ['at-tin', 'tin', 'the fig'] },
  96: { ar: 'العلق', ku: 'عەلەق', en: ['al-alaq', 'alaq', 'the clot'] },
  97: { ar: 'القدر', ku: 'قەدر', en: ['al-qadr', 'qadr', 'the power'] },
  98: { ar: 'البينة', ku: 'بەییینە', en: ['al-bayyinah', 'bayyinah', 'the clear proof'] },
  99: { ar: 'الزلزلة', ku: 'زەلزەلە', en: ['az-zalzalah', 'zalzalah', 'the earthquake'] },
  100: { ar: 'العاديات', ku: 'عادیات', en: ['al-adiyat', 'adiyat', 'the courser'] },
  101: { ar: 'القارعة', ku: 'قاریعە', en: ['al-qariah', 'qariah', 'the calamity'] },
  102: { ar: 'التكاثر', ku: 'تەکاسور', en: ['at-takathur', 'takathur', 'the rivalry'] },
  103: { ar: 'العصر', ku: 'عەسر', en: ['al-asr', 'asr', 'the declining day'] },
  104: { ar: 'الهمزة', ku: 'هومەزە', en: ['al-humazah', 'humazah', 'the traducer'] },
  105: { ar: 'الفيل', ku: 'فیل', en: ['al-fil', 'fil', 'the elephant'] },
  106: { ar: 'قريش', ku: 'قورەیش', en: ['quraysh', 'quraish'] },
  107: { ar: 'الماعون', ku: 'ماعون', en: ['al-maun', 'maun', 'the small kindnesses'] },
  108: { ar: 'الكوثر', ku: 'کەوسەر', en: ['al-kawthar', 'kawthar', 'the abundance'] },
  109: { ar: 'الكافرون', ku: 'کافیرون', en: ['al-kafirun', 'kafirun', 'the disbelievers'] },
  110: { ar: 'النصر', ku: 'نەسر', en: ['an-nasr', 'nasr', 'the divine support'] },
  111: { ar: 'المسد', ku: 'مەسەد', en: ['al-masad', 'masad', 'lahab', 'the palm fiber'] },
  112: { ar: 'الإخلاص', ku: 'ئیخلاس', en: ['al-ikhlas', 'ikhlas', 'the sincerity'] },
  113: { ar: 'الفلق', ku: 'فەلەق', en: ['al-falaq', 'falaq', 'the daybreak'] },
  114: { ar: 'الناس', ku: 'ناس', en: ['an-nas', 'nas', 'mankind'] },
};
