// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the authenticated Central Tech Platform user (id, email) so the caller can confirm which account the MCP session is acting as.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-locations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) {
    throw new Error("Supabase URL / publishable key not configured");
  }
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-locations.ts
var list_locations_default = defineTool2({
  name: "list_locations",
  title: "List locations",
  description: "List the signed-in user's business locations (branches) with their id, name, and address.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("locations").select("id,name,address,created_at").order("created_at", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { locations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool3({
  name: "list_expenses",
  title: "List expenses",
  description: "List the signed-in user's expenses for a given month (YYYY-MM), optionally filtered by location. Returns up to 500 rows sorted by day.",
  inputSchema: {
    month_key: z.string().regex(/^\d{4}-\d{2}$/).describe("Month in YYYY-MM format, e.g. '2026-07'."),
    location_id: z.string().uuid().optional().describe("Optional location UUID to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month_key, location_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("expenses").select("id,day,month_key,description,expense_type,amount,location_id,created_at").eq("month_key", month_key).order("day", { ascending: true }).limit(500);
    if (location_id) q = q.eq("location_id", location_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { month_key, expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-incomes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_incomes_default = defineTool4({
  name: "list_incomes",
  title: "List incomes",
  description: "List the signed-in user's incomes for a given month (YYYY-MM), optionally filtered by location. Returns up to 500 rows sorted by day.",
  inputSchema: {
    month_key: z2.string().regex(/^\d{4}-\d{2}$/).describe("Month in YYYY-MM format, e.g. '2026-07'."),
    location_id: z2.string().uuid().optional().describe("Optional location UUID to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month_key, location_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("incomes").select("*").eq("month_key", month_key).order("day", { ascending: true }).limit(500);
    if (location_id) q = q.eq("location_id", location_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { month_key, incomes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sales.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_sales_default = defineTool5({
  name: "list_sales",
  title: "List sales",
  description: "List the signed-in user's cigarette sales for a given month (YYYY-MM), optionally filtered by location. Returns up to 500 rows sorted by day.",
  inputSchema: {
    month_key: z3.string().regex(/^\d{4}-\d{2}$/).describe("Month in YYYY-MM format, e.g. '2026-07'."),
    location_id: z3.string().uuid().optional().describe("Optional location UUID to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month_key, location_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("sales").select("*").eq("month_key", month_key).order("day", { ascending: true }).limit(500);
    if (location_id) q = q.eq("location_id", location_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { month_key, sales: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dbmxnhsnipbpycmdmmer";
var mcp_default = defineMcp({
  name: "central-tech-platform-mcp",
  title: "Central Tech Platform",
  version: "0.1.0",
  instructions: "Tools for Central Tech Platform (CTP). Use `whoami` to confirm the signed-in account, `list_locations` to see the user's branches, and `list_expenses` / `list_incomes` / `list_sales` to read their finance records for a given month (YYYY-MM). All tools act as the signed-in user under Row Level Security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_locations_default, list_expenses_default, list_incomes_default, list_sales_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
